name: CI
on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: 1.1.13
            token: ${{ secrets.GITHUB_TOKEN }} 

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun bundle
      - name: Assets cloning...
        run: |
          cp node_modules/quill/dist/quill.snow.css ./dist/quill.snow.css
          cp node_modules/quill/dist/quill.bubble.css ./dist/quill.bubble.css
      - name: Building demo source...
        run: |
          cd demo && bun install && bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Building with jekyll...
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./demo/dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy_demo:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4