name: CI
on:
  push:
    branches:
      - main
      # - develop

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: 1.1.13

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun bundle
      # Copy quill.snow.css to desired location
      - run: cp node_modules/quill/dist/quill.snow.css ./dist/quill.snow.css
      - run: cp node_modules/quill/dist/quill.bubble.css ./dist/quill.bubble.css