name: CI
on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      MODE: 'production'
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: 1.1.13
            token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Check Environment Mode
        run: echo "Environment Mode is $MODE"
      - run: bun install
      - run: bun bundle
      - run: bun run bundle:declaration
      - name: Assets cloning...
        run: |
          cp node_modules/quill/dist/quill.snow.css ./dist/quill.snow.css
          cp node_modules/quill/dist/quill.bubble.css ./dist/quill.bubble.css
      - name: Zip bundle file
        run: |
          zip -r bundle.zip ./dist
      - name: Upload ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: bundle.zip
  clone_demo:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: build
    env:
      MODE: 'production'
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
              bun-version: 1.1.13
      - name: Check Environment Mode
        run: echo "Environment Mode is $MODE"
      - name: Building demo source...
        run: |
          cd demo && bun install &&  bun packages:version && bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Building with jekyll...
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./demo/dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy_demo:
    if: github.ref == 'refs/heads/develop'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: clone_demo
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4