name: Deploy static demo content to Pages

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing bun...
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.13
      - name: Building source...
        run: cd demo && bun install && bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build...
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./demo/dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
